### ISSUE TITLE
git reset --hard deletes files without asking

### ISSUE THREAD

**Issue by zoechi** [a14n/dart-ghpages-generator#10]
I check in my home directory into a github repo (with a lot of .gitignore) to have versioning for my settings.
When I tried your dart-ghpages-generator with a wrong `--root-dir` (probably related to one of the issues I reported recently) the `git reset --hard` deleted all files which were not yet checked in (no harm just a few changes to WebStorm keyboard shortcuts I have to set again).
But this could cause serious damage and I thing the package should check for not checked-in files and warn/ask before executing `reset`.

**Comment by a14n** [comment]
Strange... The `git reset --hard` is done in the `work_dir` that is a temp directory. The `root-dir` shouldn't be touched.

**Comment by a14n** [comment]
`work_dir` is build next to the `root-dir` folder (see https://github.com/a14n/dart-ghpages-generator/blob/01e428213185455b24b31ce3e34ca46a1e0dceaa/lib/ghpages_generator.dart#L93-L94 and https://github.com/a14n/dart-ghpages-generator/blob/01e428213185455b24b31ce3e34ca46a1e0dceaa/lib/ghpages_generator.dart#L251-L252)

**Comment by zoechi** [comment]
I don't know what exactly went wrong but AFAIR there was an error that the directory couldn't be created and then it seems to have worked on the parent.
My source directories are in `~/dart` and `~` is also a Git repo and it seems to have affected `~` instead.

**Comment by a14n** [comment]
hummm... [work_dir creation](https://github.com/a14n/dart-ghpages-generator/blob/01e428213185455b24b31ce3e34ca46a1e0dceaa/lib/ghpages_generator.dart#L154) should throw if the creation fails.

I wonder if any other tools in your env is messing up with the created work_dir.

I don't really understand what is going on. Can you reproduce the issue or the following execution has succeeded ?

**Comment by zoechi** [comment]
I guess not. I tried to figure out how to use the ghpages-generator and suddenly a few things I changed the hours before (new aliases and similar) didn't work in new terminal windows anymore then I saw that my home didn't have any uncommited files anymore (and I think the branch was `gh-pages`) and I looked through the code of your package and suspected this statement.

**Comment by a14n** [comment]
Isn't the previous execution (before the fix of #9) that has destroy your dir ?

**Comment by zoechi** [comment]
I was definitely before the fix but I don't know if it still can happen. 
Losing unrelated files can cause quite some damage therefore I created this issue.

**Comment by a14n** [comment]
Again sorry for that :-/

The bugs with code that modifies the FS are really hard for user.

I guess I can close the issue for now. Don't hesitate to re-open if you face this issue again.

**Comment by zoechi** [comment]
If you checked again and are confident this can't happen anymore then it's fine. 
Nothing bad happened - except that I was somewhat startled ;-)
