### ISSUE TITLE
Widen args dependency to include 1.x.x releases

### ISSUE THREAD

**Issue by nshahan** [a14n/dart-ghpages-generator#11]
Args released a 1.0.0 version in June 2017 with a documented breaking change. https://pub.dartlang.org/packages/args#-changelog-tab-

It looks like keeping the existing behavior would be a simple replacement `new ArgParser();` --> `new ArgParser(allowTrailingOptions: false);`

To make dependency version solving easier would you be open to releasing an update with a wider dependency on the args package to include 1.x.x releases?

**Comment by a14n** [comment]
Fixed by d614333274dc900ee1bfb48c0580d722282c0b86

A version 0.3.1 has just been published to allow arg `<2.0.0`.
